
# run_ppo.py
from reward_model import RewardModel
from ppo_rlhf import PPOTrainer

# 你自己的 prompt 列表，可以直接用 compare_model.py 里那套 10 个 prompt
PROMPTS = [
    "Write a positive one-sentence review about a restaurant.",
    "Write a short positive review about the food quality.",
    "Write a warm and enthusiastic review about the service.",
    "Write a one-sentence praise for a café.",
    "Write a cheerful review about a bakery.",
    "Write a positive comment about a dinner experience.",
    "Write a highly positive review about a Japanese restaurant.",
    "Write a positive review about the ambiance of a place.",
    "Write a review praising a friendly staff member.",
    "Write a positive sentence describing the taste of the dessert.",
    "Write a positive review about an Italian restaurant.",
    "Write a positive review about delicious noodles.",
    "Write a positive, energetic review about a brunch spot.",
    "Write a happy one-sentence review about fresh sushi.",
    "Write a one-sentence compliment for a fast food place.",
    "Write a positive review about the freshness of the ingredients.",
    "Write an encouraging review about a newly opened café.",
    "Write a one-sentence review about excellent customer service.",
    "Write a heartwarming review about a neighborhood bakery.",
    "Write a positive review about a cozy coffee shop.",
    "Write a cheerful one-sentence review for great drinks.",
    "Write a positive review about spicy dishes.",
    "Write a positive description of a well-priced meal.",
    "Write a quick positive review about a steakhouse.",
    "Write a one-line compliment for a barista.",
    "Write a positive sentence about crispy fried chicken.",
    "Write a positive review about savory dumplings.",
    "Write a joyful review about a restaurant with great atmosphere.",
    "Write a one-sentence appreciation for good vegetarian options.",
    "Write a positive review about refreshing beverages.",
    "Write a review complimenting a polite waiter.",
    "Write a review praising handmade noodles.",
    "Write a positive sentence about creamy pasta.",
    "Write a one-sentence appreciative review about a bakery’s croissants.",
    "Write a positive description of a well-balanced meal.",
    "Write a short review about affordable and tasty food.",
    "Write a one-sentence praise of a fun dining experience.",
    "Write a positive review about creative dishes.",
    "Write a cheerful review about great cocktails.",
    "Write a positive comment on a food truck.",
    "Write a one-line praise for a friendly server.",
    "Write a positive review about soft and fluffy pancakes.",
    "Write one sentence praising a new fusion restaurant.",
    "Write a positive review about aromatic coffee.",
    "Write a compliment about freshly baked bread.",
    "Write a review celebrating the flavor of spicy wings.",
    "Write a one-sentence positive comment about a wine bar.",
    "Write an energetic review about flavorful ramen.",
    "Write a positive review about tender steak.",
    "Write a heartwarming comment about a small family restaurant.",
    "Write a positive review about a quiet café.",
    "Write a one-sentence praise of creamy milk tea.",
    "Write a bright review about delicious tacos.",
    "Write a positive line about well-crafted cocktails.",
    "Write a happy review about a satisfying lunch special.",
    "Write a positive review about a seafood restaurant.",
    "Write a one-sentence review about great breakfast.",
    "Write a kind comment praising a local diner.",
    "Write a positive review about tasty rice bowls.",
    "Write a sweet review about a pastry shop.",
    "Write a one-line compliment for a Korean BBQ place.",
    "Write a positive description about fresh salads.",
    "Write a cheerful review of a sushi buffet.",
    "Write a positive comment on a great dessert menu.",
    "Write a motivating review about a restaurant with healthy options.",
    "Write a positive praise for a lively bar.",
    "Write a review appreciating excellent presentation on dishes.",
    "Write a positive one-liner about flavorful curry.",
    "Write a short review about juicy burgers.",
    "Write a positive review about crunchy fries.",
    "Write a cheerful sentence about delicious pho.",
    "Write a positive review about a charming cafe environment.",
    "Write a positive review about well-seasoned grilled items.",
    "Write a one-line praise about amazing udon.",
    "Write a positive review about a dessert that exceeded expectations.",
    "Write a positive one-sentence review about a refreshing smoothie.",
    "Write a kind comment about polite staff and fast service.",
    "Write a one-line praise for a bakery with soft pastries.",
    "Write an energetic sentence praising hot pot flavor.",
    "Write a short positive review about an exceptional dining experience.",
    "Write a strong negative review about a restaurant.",
    "Write a one-sentence complaint about slow service.",
    "Write a negative review about bad hygiene at a café.",
    "Write a complaint about overpriced dishes.",
    "Write a negative one-liner about rude staff.",
    "Write a one-sentence complaint about cold food.",
    "Write a critical review about soggy fries.",
    "Write a harsh complaint about burnt toast.",
    "Write a negative review about undercooked meat.",
    "Write a disappointed review about flavorless pasta.",
    "Write a negative review about a noisy environment.",
    "Write a complaint about long waiting times.",
    "Write a one-sentence negative comment on poor customer service.",
    "Write a complaint about a dirty restroom.",
    "Write a review expressing disappointment in the taste.",
    "Write a negative review about over-salted food.",
    "Write a complaint about an unfriendly cashier.",
    "Write a review criticizing bland soup.",
    "Write a negative line about a terrible dining experience.",
    "Write a critical review of poorly maintained tables.",
    "Write a complaint about a wrong order.",
    "Write a negative review about stale bread.",
    "Write a complaint about watery drinks.",
    "Write a negative review about cold and dry chicken.",
    "Write a one-liner criticizing bad coffee.",
    "Write a review complaining about small portion size.",
    "Write a negative complaint about burnt pizza.",
    "Write a harsh review about extremely slow service.",
    "Write a negative comment about unpleasant smell.",
    "Write a one-line complaint about overpriced snacks.",
    "Write a negative review about awful seasoning.",
    "Write a complaint about careless packaging.",
    "Write a review criticizing soggy nachos.",
    "Write a one-liner about inconsistent quality.",
    "Write a negative review about broken chairs.",
    "Write a disappointed review about bland curry.",
    "Write a complaint about a dirty kitchen.",
    "Write a negative review about chaotic management.",
    "Write a critical review about missing ingredients.",
    "Write a negative review about low-value set meals.",
    "Write a complaint about loud and disruptive staff.",
    "Write a review criticizing burnt pastries.",
    "Write a harsh review about the worst burger ever.",
    "Write a negative review about overcooked vegetables.",
    "Write a complaint about poorly packaged takeout.",
    "Write a one-liner criticizing flavorless drinks.",
    "Write a review expressing frustration with slow checkout.",
    "Write a negative comment about oily dishes.",
    "Write a complaint about poor seating arrangement.",
    "Write a harsh review about inconsistent service.",
    "Write a negative review about old and stale desserts.",
    "Write a complaint about tasteless tea.",
    "Write a review criticizing watery curry.",
    "Write a negative comment about dry noodles.",
    "Write a harsh review about untrained staff.",
    "Write a one-sentence complaint about missing utensils.",
    "Write a negative review about uncooked rice.",
    "Write a complaint about an unprofessional manager.",
    "Write a disappointed review about bland pancakes.",
    "Write a negative review about a dirty dining area.",
    "Write a complaint about a cold, unwelcoming environment.",
    "Write a negative one-liner about poor drink preparation.",
    "Write a review criticizing lack of flavor.",
    "Write a disappointed review about a failed dining experience.",
    "Write a one-sentence complaint about chaotic service.",
    "Write a negative review about a salad with wilted vegetables.",
    "Write a critical line about greasy food.",
    "Write a complaint about tasteless meat.",
    "Write a harsh review about terrible coffee.",
    "Write a negative comment about a disappointing dessert.",
    "Write a one-line complaint about stale cookies.",
    "Write a negative review about unseasoned fries.",
    "Write a complaint about inattentive service.",
    "Write a harsh review about too much grease.",
    "Write a negative review about an unpleasant overall experience.",
    "Write a one-sentence complaint about unappetizing appetizers.",
    "Write a negative comment on bland rice bowls.",
    "Write a disappointed review about weak drinks.",
    "Write a critical review about poorly prepared seafood.",
    "Write a harsh complaint about the worst noodles ever.",
    "Objectively describe the dishes at a Chinese restaurant.",
    "Provide a neutral one-sentence description of a dining environment.",
    "Write an objective comment about the seating arrangement.",
    "Give a neutral description of restaurant accessibility.",
    "Describe the menu variety in one objective sentence.",
    "Write a factual one-sentence description of takeout service.",
    "Write a neutral comment about available beverages.",
    "Objectively describe the arrangement of the tables.",
    "Write a neutral description of a standard lunch meal.",
    "Objectively describe the portion size of a meal.",
    "Write a neutral one-sentence comment on the waiting time.",
    "Describe the lighting in a neutral tone.",
    "Give an objective description of the restaurant layout.",
    "Provide a neutral comment about cleanliness.",
    "Write an objective comment about pricing.",
    "Write a neutral one-sentence description of a typical breakfast set.",
    "Objectively describe a self-service counter.",
    "Write a neutral comment about the restaurant’s decoration.",
    "Describe the noise level in a factual way.",
    "Objectively describe the arrangement of utensils.",
    "Write a neutral comment about the smell in the dining area.",
    "Provide a factual statement about staff uniforms.",
    "Objectively describe a standard beverage.",
    "Write a neutral description of a typical appetizer.",
    "Objectively describe dish presentation.",
    "Write a neutral comment about available condiments.",
    "Write an objective line describing the outdoor seating.",
    "Provide a neutral description of the music in the restaurant.",
    "Write a factual comment about the restaurant's hours.",
    "Objectively describe the ordering process.",
    "Write a neutral comment about dining space.",
    "Objectively describe how a dish is served.",
    "Provide a factual statement about the menu layout.",
    "Objectively describe the dessert section.",
    "Write a neutral line describing a beverage dispenser.",
    "Provide an objective description of typical side dishes.",
    "Give a factual description of the staff workflow.",
    "Objectively describe the kitchen setup seen from the dining area.",
    "Write a neutral comment about parking availability.",
    "Objectively describe beverage presentation.",
       "Write a neutral comment about parking availability.",
    "Objectively describe the layout and seating arrangement of the restaurant.",
    "Briefly explain whether the restaurant is suitable for large groups.",
    "Describe the lighting and overall atmosphere in a neutral tone.",
    "Give a neutral comment about the restaurant’s accessibility.",
    "Provide a factual description of the menu variety.",
    "Objectively state whether the restaurant is kid-friendly.",
    "Write an unbiased description of the restaurant's noise level.",
    "Briefly describe the location and nearby surroundings.",
    "Write a neutral observation about the restaurant's wait time.",
    "Write a positive review praising the fresh ingredients.",
    "Give an enthusiastic compliment about the friendly staff.",
    "Write a cheerful comment about the excellent desserts.",
    "Describe how amazing the pasta tasted in an excited tone.",
    "Write an uplifting review celebrating the delicious noodle soup.",
    "Give a warm and heartwarming review about a family dinner.",
    "Write a highly enthusiastic review of a newly opened café.",
    "Praise the restaurant’s outstanding customer service.",
    "Write a positive remark about the beautifully plated dishes.",
    "Give an energetic recommendation for the signature ramen.",
    "Write a harsh complaint about the rude waiter.",
    "Describe how terrible the food quality was in a strong negative tone.",
    "Write a negative review about the slow service.",
    "Complain about the cold and undercooked dishes.",
    "Write a strong warning about overpriced food.",
    "Give a negative comment about the chaotic management.",
    "Write a harsh criticism of the burnt pizza.",
    "Complain about the long waiting time and poor organization.",
    "Describe the restaurant’s hygiene issues in a negative tone.",
    "Write a strong negative comment about the weird smell inside.",
    "Write a neutral description about beverage options.",
    "Objectively describe the tableware and utensils.",
    "Write a factual comment about the restaurant’s interior design.",
    "Describe the ordering process in a neutral tone.",
    "Provide an unbiased statement about delivery speed.",
    "Write a neutral comparison between dine-in and takeout options.",
    "Give a factual description of the drink menu layout.",
    "Explain the reservation process in a neutral tone.",
    "Briefly describe the restaurant's hours without emotional tone.",
    "Write an objective comment about portion sizes.",
    "Give a positive comment about the restaurant’s warm ambiance.",
    "Write a short excited review about the tasty sushi.",
    "Praise the excellent wine selection enthusiastically.",
    "Write a cheerful comment about a memorable dining experience.",
    "Give an excited review of the restaurant's signature steak.",
    "Write a joyful compliment about the perfectly cooked seafood.",
    "Write an uplifting remark about the generous serving sizes.",
    "Give a positive review praising the friendly barista.",
    "Write an enthusiastic comment about the refreshing drinks.",
    "Write a negative review about the greasy food.",
    "Complain about the burnt taste of the grilled dishes.",
    "Write a strong negative comment about inconsistent seasoning.",
    "Describe the unprofessional staff in a harsh tone.",
    "Write a negative warning about food safety concerns.",
    "Complain about the extremely slow customer service.",
    "Write a negative review about the small portion sizes.",
    "Write a harsh remark about the weird texture of the soup.",
    "Give a negative comment about the dirty tables.",
    "Write a neutral comment about the restaurant’s music volume.",
    "Objectively describe how crowded the restaurant usually is.",
    "Write a neutral assessment of the lunchtime menu.",
    "Describe the payment process without expressing emotion.",
    "Write a neutral description of the staff uniforms.",
    "Provide an unbiased observation about the drink refill speed.",
    "Objectively compare two dishes without sentiment.",
    "Describe the entrance area in a neutral tone.",
    "Write a factual comment about the bathroom layout.",
    "Write a neutral description about the seasoning level of dishes.",
    "Give a positive review of the excellent breakfast menu.",
    "Write a cheerful review of the sweet and delicious pastries.",
    "Praise the restaurant's fast and polite service.",
    "Write a joyful comment about the cozy interior.",
    "Describe how amazing the desserts were in an enthusiastic tone.",
    "Give a positive remark about the well-prepared appetizers.",
    "Write an uplifting comment about the great brunch experience.",
    "Write an excited review of an unforgettable dinner.",
    "Write a positive recommendation for the seafood platter.",
    "Write a negative complaint about the watery sauce.",
    "Describe the stale bread in a strong negative tone.",
    "Write a harsh comment about the bad coffee quality.",
    "Complain about the overly salty dishes.",
    "Write a negative review criticizing the bland flavors.",
    "Give a strong complaint about the extremely high prices.",
    "Write a negative comment about the long delivery time.",
    "Write a harsh warning about the noisy environment.",
    "Complain about the limited seating availability.",
    "Write a negative remark about the unhelpful staff.",
    "Objectively describe the restaurant's décor style.",
    "Give a neutral statement about the air conditioning.",
    "Write a factual description of the menu organization.",
    "Describe the seating capacity in a neutral tone.",
    "Write a neutral comment about the water quality.",
    "Provide an unbiased description of the side dish options.",
    "Write a factual remark about the restaurant’s popularity.",
    "Describe the availability of vegetarian options neutrally."
]



def main():
    # 1. 初始化 RewardModel（judge）
    rm = RewardModel()

    # 2. 从 SFT 模型初始化 PPO
    sft_model_path = "../models/sft_model"
    trainer = PPOTrainer(model_path=sft_model_path, reward_fn=rm.compute_reward)

    # 3. PPO 训练
    trainer.train(PROMPTS)

    # 4. 保存 RLHF 模型
    rlhf_save_path = "../models/rlhf_model"
    trainer.save_policy(rlhf_save_path)


if __name__ == "__main__":
    main()